/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package sparktest

//import org.apache.spark.sql.SparkSession


object App {
  def main(args: Array[String]): Unit = {
    println(greeting())
    //val spark:SparkSession = SparkSession.builder()
    //  .master("local[1]")
    //  .appName("SparkByExamples.com")
    //  .getOrCreate()   
  }

  def greeting(): String = "Hello, world!"
}
